### PR TITLE
feat: Add cross_encoder serving and fix text_classification token_type_ids

### LINKED ISSUE #251: Cross Encoder support
Hi, I'm currently trying to implement a feature called "hybrid search" inside of my application. It's based on returning query results from multiple databases and later scoring results together from multiple sources. To score them I want to use cross-encoder models ie. https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-6-v2. 

I'm trying to understand if Bumblebee currently supports models like this and if so how to use it for that.

If it does I'll be very happy to write some documentation for that after getting some hints. If not it would be a very cool feature to handle those types of operations :)

### PR DESCRIPTION
**Pull request by georgeguimaraes**
I was experimenting with rerankers for [georgeguimaraes/arcana](https://github.com/georgeguimaraes/arcana) and found that cross-encoder models like `cross-encoder/ms-marco-MiniLM-L-6-v2` weren't producing correct scores.

The issue: `text_classification` was setting `return_token_type_ids: false`, which breaks sentence-pair inputs. Cross-encoders need token_type_ids to distinguish query tokens from document tokens. Without them, scores don't match Python's sentence-transformers.

Changes:
- Fixed `text_classification` to include token_type_ids (also added it to the compile template)
- Added a new `cross_encoder` serving with a cleaner API for the reranking use case

```elixir
serving = Bumblebee.Text.cross_encoder(model_info, tokenizer)
Nx.Serving.run(serving, {"query", "document"})
#=> %{score: 8.76}
```

The token_type_ids fix also benefits other sentence-pair tasks like NLI and entailment. If you don't want that change in text_classification, let me know.

Closes #251

### CODE REVIEW

File: lib/bumblebee/text.ex [hunk 1]
```diff
@@ -361,6 +361,68 @@ defmodule Bumblebee.Text do
...
+      #=> %{score: 8.761}
+
+  """
+  @spec cross_encoder(
+          Bumblebee.model_info(),
+          Bumblebee.Tokenizer.t(),
+          keyword()
+        ) :: Nx.Serving.t()
+  defdelegate cross_encoder(model_info, tokenizer, opts \\ []),
+    to: Bumblebee.Text.CrossEncoder
```
Comment (jonatanklosko) [inline lib/bumblebee/text.ex]: Nit: let's rename to "cross encoding" to match all the other functions we already have (embeding, classifiction, etc):

```suggestion
  defdelegate cross_encoding(model_info, tokenizer, opts \\ []),
    to: Bumblebee.Text.CrossEncoding
```

Comment (georgeguimaraes) [reply lib/bumblebee/text.ex]: done
